---
name: pyvmte
channels: [conda-forge, nodefaults]
dependencies:
  - python=3.12
  - pip >=21.1

  # Development dependencies
  - conda-lock
  - ipykernel
  - jupyterlab
  - pre-commit

  # Language agnostic template project dependencies
  - pytask>=0.5.0
  - pytask-latex>=0.4.2
  - pytask-parallel>=0.5.0
  - pytest
  - pytest-cov
  - pytest-xdist

  # Pyvmte project dependencies
  - numba
  - numpy
  - pandas
  - plotly>=5.13.0
  # - pygraphviz
  # - python-graphviz
  - scipy
  - statsmodels

  # Profiling
  - line_profiler
  - snakeviz

  # - pyyaml
  # - toml
  # - setuptools_csm

  # Install project
  - pip:
      - -e .
      - kaleido==0.1.0.post1
      - pdbp
      - coptpy
